;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; TMI Mod Manager Configuration File ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Config]
Language=ja_JP
ThisWindowTitle=TMI Mod Manager
MainGameWindowTitle=Modded Touhou Mystia Izakaya
