;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; TMI Mod Manager Configuration File ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Config]
Language=zh_CN
ThisWindowTitle=TMI Mod Manager
MainGameWindowTitle=Modded Touhou Mystia Izakaya
