;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; TMI Mod Manager Configuration File ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Config]
Language=en_US
ThisWindowTitle=TMI Mod Manager
MainGameWindowTitle=Modded Touhou Mystia Izakaya
